version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_app
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: node_api
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "5000"
